### ISSUE TITLE
[PATCH] Fix spelling error in manpage

### ISSUE THREAD

**Issue by carnil** [rjbs/App-Cmd#53]
Hi,

In Debian we are currently applying the following patch to App-Cmd.
We thought you might be interested in it too.

    Description: Fix spelling error in manpage
    Origin: vendor
    Author: Salvatore Bonaccorso <carnil@debian.org>
    Last-Update: 2015-09-04
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libapp-cmd-perl.git/plain/debian/patches/spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by rjbs** [comment]
Thanks!

I have applied this to git master.  It will be in the next release.
