### ISSUE TITLE
App::Cmd object not blessed before call to _command

### ISSUE THREAD

**Issue by lucastheisen** [rjbs/App-Cmd#57]
This is really confusing and makes plugin development harder.  If instead of this:

```
sub new {
  my ($class, $arg) = @_;

  my $arg0 = $0;
  my $base = File::Basename::basename $arg0;

  my $self = {
    command      => $class->_command($arg),
    arg0         => $base,
    full_arg0    => $arg0,
    show_version => $arg->{show_version_cmd} || 0,
  };

  bless $self => $class;
}
```

We used this:

```
sub new {
  my ($class, $arg) = @_;
  my $arg0 = $0;
  my $base = File::Basename::basename $arg0;

  my $self = bless({}, $class);
  $self->{command} = $self->_command($arg);
  $self->{arg0} = $base;
  $self->{full_arg0} = $arg0;
  $self->{show_version} = $arg->{show_version_cmd} || 0;

  return $self;
}
```

Then customized override methods (like plugin_search_path) would have access to the `$self` instance.  I use a different model (registration based rather than detected) fro my plugins and I would rather only parse my config once.  So i want to store the config instance in `$self`.

Also, it is quite confusing to be using `$self` variable throughout when it is actually `$class`...

Are you accepting pull requests?  I would create one if you would like...

**Comment by rjbs** [comment]
PRs are welcome!  In the example given, I suggest creating `$self` with all the known data, then calling `_command` on that, rather than blessing the empty hash.

**Comment by lucastheisen** [comment]
I have submitted this pull request:  blessed self before calling _command in App::Cmd->new #60 

Out of curiosity, why do you prefer 

> creating $self with all the known data, then calling _command on that, rather than blessing the empty hash

My convention is:

```
package Foo::Bar;

sub new {
    return bless({}, shift)->_init(@_);
}

sub _init {
    my ($self, $foo, $bar) = @_

    # initialize here
    $self->{foo} = $foo;
    $self->{bar} = $bar;

    return $self;
}
```

I read once, many years back, that breaking it up like that made it easier to inherit:

```
package Foo::Bar::Baz;
use parent Foo::Bar

sub _init(
    my ($self, $foo, $bar, $baz) = @_;

    $self->Foo::Bar::_init($foo, $bar);
    $self->{baz} = $baz;

    return $self;
}
```

**Comment by lucastheisen** [comment]
Resolved by https://github.com/rjbs/App-Cmd/pull/60#event-761969308
