### ISSUE TITLE
should broken commands be fatal?

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/App-Cmd#58]
I see that there are unit tests for broken commands, which suggests it's intentional that using a broken command module should be fatal. But is this the best behaviour?

I would propose wrapping the `load_class($plugin)` call on 195 with a `try{}` block, and instead warning with the exception message. This would at least not cause an entire application to fail if a broken plugin is installed.

For example, Dist::Zilla::App::Command::podpreview currently won't load (https://rt.cpan.org/Ticket/Display.html?id=110342) because Perl6::Export::Attrs is broken in blead. This results in a broken `dzil` application if the podpreview command is installed.

example test failure: http://www.cpantesters.org/cpan/report/e1a1ab84-f7d1-11e5-978c-a77dfcd2507e

**Comment by rjbs** [comment]
I *do* think they should be fatal.  If the program is meant to load plugins, but can't, and then proceeds without them, the warning is likely to be missed.

What I'd really like is a simple way to say "only load some standard set of plugins."  Once again, Module::Pluggable has come back to bite me in the rear.  This would be the standard thing to do in testing: you'd get an App::Cmd (or, in this case, a Dist::Zilla::App) with only its core plugins loaded.

How does `podpreview` get installed on blead if it won't load?

Also, that test failure link fails for me… but I know the kind of error you're talking about.

I have created #59 to replace this.
