### ISSUE TITLE
Peculiar warning about binary versions

### ISSUE THREAD

**Issue by PaulGWebster** [rjbs/App-Cmd#73]
# My application is called 'oe'

## Env
perlbrew - v5.32.0

## Console
» oe help
Util.c: loadable library and perl binaries are mismatched (got handshake key 0xc180000, needed 0xe180000)

**Comment by rjbs** [comment]
Hey, Paul.  This isn't going to be an App::Cmd bug. You've gotten compiled object files (from a C extension) for one version of perl into the @INC directories of another version of Perl.  When you try to load an XS extension, there's a "handshake" to make sure versions match, and yours don't.  App::Cmd has no C, so it can't be the cause.
