### ISSUE TITLE
App::Cmd is lacking an `appcmd` to initialize apps using App::Cmd

### ISSUE THREAD

**Issue by oodler577** [rjbs/App-Cmd#74]
e.g., `dancer2` uses App::Cmd

**Comment by oodler577** [comment]
that title was too close to symmetry to ignore :)

**Comment by rjbs** [comment]
Are you saying "there should be a program you run to initialize a distribution that is itself an App::Cmd project"?

**Comment by oodler577** [comment]
Yes. I'm happy to create a such a thing if you think that it'd be generally useful. Ended up just copy and pasting your examples and changing the namespaces to suite my needs. What do you think?

**Comment by rjbs** [comment]
This sounds like it should be a Dist::Zilla minting profile, and not part of App::Cmd.

**Comment by oodler577** [comment]
Cool, will check it out. And will close this issue in the meantime. Thanks!
