### ISSUE TITLE
Adding a simple text-based user interface

### ISSUE THREAD

**Issue by iamllcoolray** [rjbs/App-Cmd#75]
Would it be possible to implement a simple text-based user interface?

For example:

```perl
my %arg = ( tui => 1, );
my $cmd = Grizzly->new( \%arg );
$cmd->run;
```
When ran:

```bash
program>
```
Something similar to the [Term::TUI]("https://metacpan.org/pod/Term::TUI") but integrated into the module.

Commands like help and quit would be enabled by default. The version command could remain disabled by default.

I hope I phrased the question properly.

**Comment by rjbs** [comment]
I understand your question very well.  I will not be implementing this.  It could be done, but I think it would be a bit of a problem to "just do".  App::Cmd expects that when an application is run, the object is instantiated, the command is found, the command is executed, and everything exits.  In a captive shell, you would need to track the state of the program better than that.

Beyond that, the input parsing would need more work.  Right now, App::Cmd can assume that @ARGV has been set by the shell, with its quoting taking care of multi-worth arguments and so on.  In a readline interface, you'd have to handle this yourself.

All that said, I think this is something that could be built by someone who wanted it, and if you built it and it's great, I'd like hearing about it.

**Comment by iamllcoolray** [comment]
I completely understand. Then I guess I'll get started on building that then. Once it's operational and great, I will definitely shoot you an email about it.
